# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm.box = "wot-base2"
	config.vm.network :forwarded_port, guest: 80, host: 8080
	config.ssh.forward_agent = true
	config.ssh.username = "wot"
	config.ssh.private_key_path = "../etc/wot-server-dsa"
	config.vm.synced_folder ".", "/vagrant", disabled: true
end
